title: Parth
email: pparth230@gmail.com
description: Writing on what I learned
baseurl: ""
url: "https://pparth230.github.io"
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
