title: Parth's Blog
email: pparth230@example.com
description: My personal blog about technology and life
baseurl: ""
url: "https://pparth230.github.io"
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
